// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOx8EZFKyW-GagFOtTvyyDoTEn8B8zwS4',
    appId: '1:23595612571:android:aac908228d73e256b0493e',
    messagingSenderId: '23595612571',
    projectId: 'movilizate-app-66676',
    storageBucket: 'movilizate-app-66676.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3yYjomPp1pN-a1EiHtDc7q5xHiiWaV3c',
    appId: '1:23595612571:ios:f05c8beffb296a19b0493e',
    messagingSenderId: '23595612571',
    projectId: 'movilizate-app-66676',
    storageBucket: 'movilizate-app-66676.firebasestorage.app',
    androidClientId: '23595612571-uj3lc2o5vbl9o27go5ph5nsuqja2cup6.apps.googleusercontent.com',
    iosClientId: '23595612571-brqgtpecitr9h3haiapav41dkun5jnbs.apps.googleusercontent.com',
    iosBundleId: 'bo.monval.movilizat',
  );

}